/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mario.view.turma.list;

import br.com.mario.model.Turma;
import br.com.mario.util.CellButtonRender;
import br.com.mario.util.tablemodel.TurmaTableModel;
import br.com.mario.view.turma.form.TurmaFormView;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author mario
 */
public class TurmaListView extends javax.swing.JFrame {

    private final TurmaListController controller;
    private final TurmaTableModel turmaTableModel;

    /**
     * Creates new form EstadoView
     */
    public TurmaListView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Lista de Turmas");

        controller = new TurmaListController(this);

        turmaTableModel = new TurmaTableModel(new ArrayList<>());
        tbTurmas.setModel(turmaTableModel);

        tbTurmas.setRowHeight(30);
        tbTurmas.getColumn("Editar").setCellRenderer(new CellButtonRender("Editar", "src/resources/ic_edit.png"));
        tbTurmas.getColumn("Remover").setCellRenderer(new CellButtonRender("Remover", "src/resources/ic_remove.png"));

        controller.loadTurmas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTurmas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbNovo.setBackground(new java.awt.Color(0, 153, 51));
        jbNovo.setForeground(new java.awt.Color(255, 255, 255));
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        tbTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTurmasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        edit(null);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void tbTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTurmasMouseClicked
        int rowSelect = tbTurmas.getSelectedRow();

        TurmaTableModel tableModel = (TurmaTableModel) tbTurmas.getModel();

        if (rowSelect != -1) {

            Turma turma = tableModel.getValueAtRow(rowSelect);

            //Edit
            if (tbTurmas.getSelectedColumn() == 5) {
                edit(turma);
            }
            //Remove
            if (tbTurmas.getSelectedColumn() == 6) {
                remove(turma);
            }
        }
    }//GEN-LAST:event_tbTurmasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNovo;
    private javax.swing.JTable tbTurmas;
    // End of variables declaration//GEN-END:variables

    /**
     * Função responsavel pela remoção
     *
     * @param turma
     */
    private void remove(Turma turma) {
        controller.remove(turma);
        controller.loadTurmas();
    }

    /*/*
     Função responsavel pela edição
     */
    private void edit(Turma turma) {
        boolean closeDialog;
        try {
            closeDialog = new TurmaFormView(this, true, turma).openDialog();
            if (closeDialog) {
                controller.loadTurmas();
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    public JButton getJbNovo() {
        return jbNovo;
    }

    public void setJbNovo(JButton jbNovo) {
        this.jbNovo = jbNovo;
    }

    public JTable getTbEstados() {
        return tbTurmas;
    }

    public void setTbEstados(JTable tbEstados) {
        this.tbTurmas = tbEstados;
    }

    public TurmaTableModel getTurmaTableModel() {
        return turmaTableModel;
    }

}
