/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mario.view.atividade.list;

import br.com.mario.model.Atividade;
import br.com.mario.util.CellButtonRender;
import br.com.mario.util.tablemodel.AtividadeTableModel;
import br.com.mario.view.atividade.form.AtividadeFormView;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author mario
 */
public class AtividadeListView extends javax.swing.JFrame {

    private final AtividadeListController controller;
    private AtividadeTableModel atividadeTableModel;

    /**
     * Creates new form EstadoView
     */
    public AtividadeListView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Lista de Atividades");

        controller = new AtividadeListController(this);

        atividadeTableModel = new AtividadeTableModel(new ArrayList<>());
        tbAtividades.setModel(atividadeTableModel);

        tbAtividades.setRowHeight(30);
        tbAtividades.getColumn("Editar").setCellRenderer(new CellButtonRender("Editar", "src/resources/ic_edit.png"));
        tbAtividades.getColumn("Remover").setCellRenderer(new CellButtonRender("Remover", "src/resources/ic_remove.png"));

        controller.loadAtividades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAtividades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbNovo.setBackground(new java.awt.Color(0, 153, 51));
        jbNovo.setForeground(new java.awt.Color(255, 255, 255));
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        tbAtividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAtividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAtividadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAtividades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        edit(null);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void tbAtividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAtividadesMouseClicked
        int rowSelect = tbAtividades.getSelectedRow();

        AtividadeTableModel tableModel = (AtividadeTableModel) tbAtividades.getModel();

        if (rowSelect != -1) {

            Atividade atividade = tableModel.getValueAtRow(rowSelect);

            //Edit
            if (tbAtividades.getSelectedColumn() == 2) {
                edit(atividade);
            }
            //Remove
            if (tbAtividades.getSelectedColumn() == 3) {
                remove(atividade);
            }
        }
    }//GEN-LAST:event_tbAtividadesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNovo;
    private javax.swing.JTable tbAtividades;
    // End of variables declaration//GEN-END:variables

    /**
     * Função responsavel pela remoção
     *
     * @param atividade
     */
    private void remove(Atividade atividade) {
        controller.remove(atividade);
        controller.loadAtividades();
    }

    /*/*
     Função responsavel pela edição
     */
    private void edit(Atividade atividade) {
        boolean closeDialog = new AtividadeFormView(this, true, atividade).openDialog();

        if (closeDialog) {
            controller.loadAtividades();
        }
    }

    public JButton getJbNovo() {
        return jbNovo;
    }

    public void setJbNovo(JButton jbNovo) {
        this.jbNovo = jbNovo;
    }

    public JTable getTbEstados() {
        return tbAtividades;
    }

    public void setTbEstados(JTable tbEstados) {
        this.tbAtividades = tbEstados;
    }

    public AtividadeTableModel getAtividadeTableModel() {
        return atividadeTableModel;
    }

    public void setAtividadeTableModel(AtividadeTableModel atividadeTableModel) {
        this.atividadeTableModel = atividadeTableModel;
    }

}
