/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mario.view.matricula.view;

import br.com.mario.model.Matricula;
import br.com.mario.util.CellButtonRender;
import br.com.mario.util.tablemodel.MatriculaTableModel;
import br.com.mario.view.matricula.form.MatriculaFormView;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author mario
 */
public class MatriculaListView extends javax.swing.JFrame {

    private final MatriculaListController controller;
    private final MatriculaTableModel matriculaTableModel;

    /**
     * Creates new form EstadoView
     */
    public MatriculaListView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Lista de Matriculas");

        controller = new MatriculaListController(this);

        matriculaTableModel = new MatriculaTableModel(new ArrayList<>());
        tbMatriculas.setModel(matriculaTableModel);

        tbMatriculas.setRowHeight(30);
        tbMatriculas.getColumn("Editar").setCellRenderer(new CellButtonRender("Editar", "src/resources/ic_edit.png"));
        tbMatriculas.getColumn("Remover").setCellRenderer(new CellButtonRender("Remover", "src/resources/ic_remove.png"));

        controller.loadMatriculas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMatriculas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbNovo.setBackground(new java.awt.Color(0, 153, 51));
        jbNovo.setForeground(new java.awt.Color(255, 255, 255));
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        tbMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMatriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMatriculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMatriculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        edit(null);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void tbMatriculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMatriculasMouseClicked
        int rowSelect = tbMatriculas.getSelectedRow();

        MatriculaTableModel tableModel = (MatriculaTableModel) tbMatriculas.getModel();

        if (rowSelect != -1) {

            Matricula matricula = tableModel.getValueAtRow(rowSelect);

            //Edit
            if (tbMatriculas.getSelectedColumn() == 3) {
                edit(matricula);
            }
            //Remove
            if (tbMatriculas.getSelectedColumn() == 4) {
                remove(matricula);
            }
        }
    }//GEN-LAST:event_tbMatriculasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNovo;
    private javax.swing.JTable tbMatriculas;
    // End of variables declaration//GEN-END:variables

    /**
     * Função responsavel pela remoção
     *
     * @param matricula
     */
    private void remove(Matricula matricula) {
        controller.remove(matricula);
        controller.loadMatriculas();
    }

    /*/*
     Função responsavel pela edição
     */
    private void edit(Matricula matricula) {
        boolean closeDialog;
        try {
            closeDialog = new MatriculaFormView(this, true, matricula).openDialog();
            if (closeDialog) {
                controller.loadMatriculas();
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    public MatriculaTableModel getMatriculaTableModel() {
        return matriculaTableModel;
    }

    public JButton getJbNovo() {
        return jbNovo;
    }

}
