/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mario.view.chamada.view;

import br.com.mario.model.Chamada;
import br.com.mario.util.CellButtonRender;
import br.com.mario.util.tablemodel.ChamadaTableModel;
import br.com.mario.view.chamada.form.ChamadaFormView;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author mario
 */
public class ChamadaListView extends javax.swing.JFrame {

    private final ChamadaListController controller;
    private final ChamadaTableModel chamadaTableModel;

    /**
     * Creates new form EstadoView
     */
    public ChamadaListView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Lista de Chamadas");

        controller = new ChamadaListController(this);

        chamadaTableModel = new ChamadaTableModel(new ArrayList<>());
        tbChamadas.setModel(chamadaTableModel);

        tbChamadas.setRowHeight(30);
        tbChamadas.getColumn("Visualizar").setCellRenderer(new CellButtonRender("Visualizar", "src/resources/ic_view.png"));

        controller.loadChamadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChamadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbNovo.setBackground(new java.awt.Color(0, 153, 51));
        jbNovo.setForeground(new java.awt.Color(255, 255, 255));
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        tbChamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbChamadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChamadasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbChamadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        edit(null);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void tbChamadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChamadasMouseClicked
        int rowSelect = tbChamadas.getSelectedRow();

        ChamadaTableModel tableModel = (ChamadaTableModel) tbChamadas.getModel();

        if (rowSelect != -1) {

            Chamada chamada = tableModel.getValueAtRow(rowSelect);

            //Edit
            if (tbChamadas.getSelectedColumn() == 3) {
                edit(chamada);
            }
        }
    }//GEN-LAST:event_tbChamadasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNovo;
    private javax.swing.JTable tbChamadas;
    // End of variables declaration//GEN-END:variables

    /*/*
     Função responsavel pela edição
     */
    private void edit(Chamada chamada) {
        boolean closeDialog;
        try {
            closeDialog = new ChamadaFormView(this, true, chamada).openDialog();
            if (closeDialog) {
                controller.loadChamadas();
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

    }

    public ChamadaTableModel getChamadaTableModel() {
        return chamadaTableModel;
    }

    public JButton getJbNovo() {
        return jbNovo;
    }

}
