/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mario.view.turma.form;

import br.com.mario.model.Atividade;
import br.com.mario.model.Instrutor;
import br.com.mario.model.Turma;
import br.com.mario.util.GenericComboBoxModel;
import java.text.ParseException;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author mario
 */
public class TurmaFormView extends javax.swing.JDialog {

    private final TurmaFormController controller;
    private final MaskFormatter mfDataInicio;
    private final MaskFormatter mfDataFim;
    private final MaskFormatter mfHora;
    private final GenericComboBoxModel<Instrutor> instrutorModel;
    private final GenericComboBoxModel<Atividade> atividadeModel;

    /**
     * Creates new form EstadoFormView1
     *
     * @param parent
     * @param modal
     * @param turma
     * @throws java.text.ParseException
     */
    public TurmaFormView(java.awt.Frame parent, boolean modal, Turma turma) throws ParseException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cadastro de Turma");

        mfDataInicio = new MaskFormatter("##/##/####");
        mfDataInicio.setPlaceholderCharacter('_');
        mfDataInicio.install(tfDataInicio);

        mfDataFim = new MaskFormatter("##/##/####");
        mfDataFim.setPlaceholderCharacter('_');
        mfDataFim.install(tfDataFim);

        mfHora = new MaskFormatter("##:##");
        mfHora.setPlaceholderCharacter('_');
        mfHora.install(tfHorario);
        
        controller = new TurmaFormController(this);

        instrutorModel = new GenericComboBoxModel<>();
        cbInstrutor.setModel(instrutorModel);
        controller.loadInstrutores();

        atividadeModel = new GenericComboBoxModel<>();
        cbAtividade.setModel(atividadeModel);
        controller.loadAtividades();

        if (turma != null) {
            controller.edit(turma);
        }

    }

    public boolean openDialog() {
        this.setVisible(true);
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        cbInstrutor = new javax.swing.JComboBox();
        cbAtividade = new javax.swing.JComboBox();
        tfDataInicio = new javax.swing.JFormattedTextField();
        tfDuracao = new javax.swing.JTextField();
        tfDataFim = new javax.swing.JFormattedTextField();
        tfHorario = new javax.swing.JFormattedTextField();
        tfNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(0, 153, 51));
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        cbInstrutor.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrutor"));

        cbAtividade.setBorder(javax.swing.BorderFactory.createTitledBorder("Atividade"));

        tfDataInicio.setBackground(new java.awt.Color(214, 217, 223));
        tfDataInicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Inicio"));
        tfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        tfDuracao.setBackground(new java.awt.Color(214, 217, 223));
        tfDuracao.setBorder(javax.swing.BorderFactory.createTitledBorder("Duração"));
        tfDuracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDuracaoKeyReleased(evt);
            }
        });

        tfDataFim.setBackground(new java.awt.Color(214, 217, 223));
        tfDataFim.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Fim"));
        tfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        tfHorario.setBackground(new java.awt.Color(214, 217, 223));
        tfHorario.setBorder(javax.swing.BorderFactory.createTitledBorder("Horário"));
        tfHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        tfNome.setBackground(new java.awt.Color(214, 217, 223));
        tfNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome)
                    .addComponent(cbInstrutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAtividade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(tfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(cbInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        controller.merge();
        dispose();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfDuracaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDuracaoKeyReleased
        checkInt();
    }//GEN-LAST:event_tfDuracaoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbAtividade;
    private javax.swing.JComboBox cbInstrutor;
    private javax.swing.JFormattedTextField tfDataFim;
    private javax.swing.JFormattedTextField tfDataInicio;
    private javax.swing.JTextField tfDuracao;
    private javax.swing.JFormattedTextField tfHorario;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    public GenericComboBoxModel<Instrutor> getInstrutorModel() {
        return instrutorModel;
    }

    public GenericComboBoxModel<Atividade> getAtividadeModel() {
        return atividadeModel;
    }

    public JButton getBtCancelar() {
        return btCancelar;
    }

    public JButton getBtSalvar() {
        return btSalvar;
    }

    public JFormattedTextField getTfDataFim() {
        return tfDataFim;
    }

    public JFormattedTextField getTfDataInicio() {
        return tfDataInicio;
    }

    public JTextField getTfDuracao() {
        return tfDuracao;
    }

    public JTextField getTfHorario() {
        return tfHorario;
    }

    public JTextField getTfNome() {
        return tfNome;
    }

    //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=METODOS=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--\\
    private void checkInt() {
        try {
            Integer.parseInt(tfDuracao.getText());
        } catch (Exception e) {
            tfDuracao.setText("");
        }
    }

}
